### ISSUE TITLE
#bug example # mutation analysis 

### ISSUE THREAD

**Issue by ZhijianZhou01** [ZhijianZhou01/BioAider#1]
When I use the function "Mutation Analysis ", I encountered an error.

```
traceback.format_exc():
Traceback (most recent call last):
  File "BioAider_develop\src\Mutation_analysis.py", line 410, in run
  File "BioAider_develop\src\my_funcyion.py", line 701, in aa_kind_dis
KeyError: ''

```

**Comment by ZhijianZhou01** [comment]
Ok, the format of sequence sets have to be fasta, and aligned based on codon method before analysis
