### ISSUE TITLE
The function of "Repeat Fragment Search" in BioAider V1.423 cannot work

### ISSUE THREAD

**Issue by ZhijianZhou01** [ZhijianZhou01/BioAider#9]
traceback.format_exc():
Traceback (most recent call last):
  File "repeat_search.py", line 335, in run
  File "my_funcyion.py", line 401, in fast_read_fasta
FileNotFoundError: [Errno 2] No such file or directory: '>TREESPARROW_HENAN_1_2004\nATGGAGAAAATAGTGCTTCTTCGTGCAATGATCAATCTTGTTAAAAGTGA\nTCAGATTGGCGTTGGTTACCATGCAGACTACTCGACAGAGCAGGGTGACA\nCAATAATGGAAAAGAACGTTACTGTTACACATGCTCAAGACATATTGGAA\nAAGACACACAACGGGAAGCTCTGCGACCTAGATGGAGTGAAGCCTCTAAT\nTTTGAAAGATTGTAGTGTAGCTGGATGGCTCCTCGGAAACCCAATGTGTG\nACGAATTCATCAATGTGCCGGAGTGGTCTTACATAGTGGAGAAGGCCAGT\nCCAGCCAATGACCTCTGTTACCCAGGGGATTTCAACGACTATGAAGAACT\nGAAACACCTATTGAGCAGAATAAACCATTTTGAAAAAATTCAGATCATCC\nCCAAAAGTTCTTGGTCCGATCATGAAGCCTCATCAGGGGTGAGCTCAGCA'

**Comment by ZhijianZhou01** [comment]
We are very sorry, some changes have caused bugs after we implemented speedup optimization in version 1.423. We will solve this problem in the next version.

We recommend that you use this function in BioAider V1.334 because it can work well.

**Comment by ZhijianZhou01** [comment]
This bug has been resolved in BioAider V1.527
